spring:
  application:
    name: skiafn-bcm-service
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
      
server:
  port: 8080
  servlet:
    context-path: /service/v2
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /application

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.skinnovation.citizen
  configuration:
    map-underscore-to-camel-case: true      

jasypt:
  encryptor:
    bean: encryptorBean
    password: xptmxm!tltmxpa#
    algorithm: PBEWithSHA256And128BitAES-CBC-BC
    poolSize: 2
