
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    connectionTimeout: 30000
    maximumPoolSize: 20
    maxLifetime: 1800000
    poolName: HikariCP
    readOnly: false
    
  redis:
    use: N
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: ${REDIS_IP}        
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    database: 0

security:
  oauth2:
    client:
      client-id: skiafn-ui
      client-secret: skiafn-ui
    resource:
      token-info-uri: http://${BCM_AUTH_IP}:${${BCM_AUTH_PORT}/oauth/check_token

bcm:
  common:
    bcm-ip: localhost
    bcm-port: 8999
    jwk-key: "signingkey"