DROP TABLE IF EXISTS MEMBER;
DROP TABLE IF EXISTS NOTICE;

CREATE TABLE MEMBER COMMENT '회원' (
    USER_ID      VARCHAR(10)	NOT NULL	COMMENT '회원ID'
  , USER_NAME    VARCHAR(100)				COMMENT '회원명'
  , USER_PASS    VARCHAR(20)	NOT NULL	COMMENT '패스워드'
  , MOBILE_NO VARCHAR(128)
  , EMAIL VARCHAR(254)
  , CONSTRAINT PK_MEMBER
  		PRIMARY KEY (USER_ID)
);

CREATE TABLE NOTICE COMMENT '게시판'(
	UUID 		CHAR(36) NOT NULL
  , TITLE		VARCHAR(50) NOT NULL 
  , DESCRIPTION 	VARCHAR(100)
  , CONSTRAINT PK_NOTICE
        PRIMARY KEY (UUID)	
);


